language: node_js

sudo: false

node_js:
  - '10'
  - '12'

before_install:
  - export PATH=$HOME/.deno/bin:$PATH

install:
  - curl -L https://deno.land/x/install/install.sh | sh -s v0.40.0
  - yarn

script:
  - yarn lint
  - yarn test
