name: Node/Deno CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Deno
        run: curl -L https://deno.land/x/install/install.sh | sh -s v0.18.0
      - name: npm install, build, and test
        run: |
          export PATH=$HOME/.deno/bin:$PATH
          yarn
          yarn lint
          yarn test
        env:
          CI: true
